from src.domain.entities.application import Application
from src.domain.interfaces import IApplicationRepository, IUserRepository
from src.services.interfaces import IApplicationService
from src.domain.interfaces import IUnitOfWork
from src.domain.entities import Sources

class ApplicationService(IApplicationService):
    __app_repo: IApplicationRepository
    __user_repo: IUserRepository
    __uow: IUnitOfWork

    def __init__(self, app_repo: IApplicationRepository, user_repo: IUserRepository, uow: IUnitOfWork, source: Sources):
        self.__app_repo = app_repo
        self.__user_repo = user_repo
        self.__uow = uow
        self.__source = source

    async def create_application(
        self, user_id: int, sender_fio: str | None, deputy_fio: str, text: str
    ) -> Application:
        async with self.__uow.atomic():
            if not sender_fio:
                user = await self.__user_repo.get_user(user_id, self.__source)
                sender_fio = f"{user.surname} {user.name} {user.patronymic or ''}".strip()
                
            app = Application(
                id=0, # Will be generated by DB
                user_id=user_id,
                sender_fio=sender_fio,
                deputy_fio=deputy_fio,
                application_text=text
            )
            return await self.__app_repo.create_application(app)

    async def get_user_applications(self, user_id: int, page: int = 0) -> tuple[list[Application], int]:
        async with self.__uow.atomic():
            count = await self.__app_repo.get_user_applications_count(user_id)
            skip = page * 4
            apps = await self.__app_repo.get_user_applications(user_id, skip=skip, limit=4)
            return apps, count

    async def get_applications_count(self, user_id: int) -> int:
        async with self.__uow.atomic():
            return await self.__app_repo.get_user_applications_count(user_id)
